# Generated by Django 4.0.4 on 2022-04-20 18:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Yoshi')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='aktyorrasmi/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Aktyor va rejissyor',
                'verbose_name_plural': 'Aktyorlar va rejissyorlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Janr nomi')),
                ('description', models.TextField()),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('tagline', models.CharField(default='', max_length=200, verbose_name='Shiori')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('poster', models.ImageField(upload_to='kino/', verbose_name='Plakat rasm')),
                ('year', models.PositiveSmallIntegerField(default=2021, verbose_name='Ishlab chiqarilish sanasi')),
                ('country', models.CharField(max_length=100, verbose_name='Mamlakati')),
                ('world_premiers', models.DateField(default=datetime.date.today, verbose_name='Jahon primyerasi')),
                ('budget', models.PositiveIntegerField(default=0, verbose_name='Byudjet')),
                ('fees_in_usa', models.PositiveIntegerField(default=0, help_text='dollar miqdorini kiriting', verbose_name="AQShda to'lovlar")),
                ('fees_in_world', models.PositiveIntegerField(default=0, help_text='Pul miqdorini kiriting', verbose_name="Dunyodagi to'lovlar")),
                ('fees_in_uz', models.PositiveIntegerField(default=0, help_text="So'm miqdorini kiriting", verbose_name="Uzbekistonda to'lovlar")),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Qoralama')),
                ('actors', models.ManyToManyField(related_name='Filimaktyori', to='main_drf.actyor', verbose_name='Aktyor')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_drf.category', verbose_name='Kategoriya')),
                ('directors', models.ManyToManyField(related_name='FilimRahbari', to='main_drf.actyor', verbose_name='Rejissyor')),
                ('genres', models.ManyToManyField(to='main_drf.janr', verbose_name='Janiri')),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
            },
        ),
        migrations.CreateModel(
            name='ReytingYulduzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mashxur reyting',
                'verbose_name_plural': 'Mashxur reytinglar',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Reyting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP manzili')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_drf.kino', verbose_name='Kino')),
                ('star', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_drf.reytingyulduzi', verbose_name='Yulduz')),
            ],
            options={
                'verbose_name': 'Reyting',
                'verbose_name_plural': 'Reytinlar',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=5000)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_drf.kino', verbose_name='Kino')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_drf.review')),
            ],
            options={
                'verbose_name': 'Ko‘rib chiqish',
                'verbose_name_plural': 'Ko‘rib chiqishlar',
            },
        ),
        migrations.CreateModel(
            name='KinoKadrlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('image', models.ImageField(upload_to='kadrrasmi/', verbose_name='Kadr_rasmlari')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_drf.kino', verbose_name='Kino')),
            ],
            options={
                'verbose_name': 'Film kadiri',
                'verbose_name_plural': 'Film Kadrlari',
            },
        ),
    ]
