# Generated by Django 4.0.4 on 2022-04-22 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_drf', '0003_alter_review_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reyting',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retings', to='main_drf.kino', verbose_name='Kino'),
        ),
    ]
